plugins: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "bin/**/*"
    - "spec/spec_helper.rb"

# Methods returning hashes shouldn't be taken care of
Metrics/MethodLength:
  CountAsOne: "hash"

RSpec/ExampleLength:
  CountAsOne: "hash"
  Max: 10 # the default is 5, wow

# I don't quite understand the logic of this rule.
# It's true that sometimes we should be splitting tests, but I see nothing wrong with multiple expectations for the same test.
RSpec/MultipleExpectations:
  Enabled: false
