plugins: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "bin/**/*"
    - "spec/spec_helper.rb"

# Methods returning hashes shouldn't be taken care of.
Metrics/MethodLength:
  CountAsOne: "hash"

Metrics/ClassLength:
  Max: 110

RSpec/ExampleLength:
  CountAsOne: "hash"
  Max: 15 # the default is 5, wow. If the test is readable...

# This rule is to enforce single expectation tests: https://www.betterspecs.org/#single
# From my experience, this creates more issues that it solves. Making spec files super long and repetitive.
# I added global aggregate_failures so we get the full list of errors instead of only the first one.
RSpec/MultipleExpectations:
  Enabled: false
